name: Bug report
about: Create a report to help us improve
title: '[Bug] '
labels:
  - bug
  - needs-triage
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      description: What type of bug is this?
      options:
        - Bug
        - Regression
        - Documentation Bug
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of whoosh-ng are you using?
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What desktop OS are you running?
      options:
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug and how to reproduce it.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      value: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots or logs to help explain your problem.
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
