import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docs: {
    Core: [
      {type: 'doc', id: 'core/index', label: 'Core'},
      'core/quickstart',
      'core/installation',
      {
        type: 'category',
        label: 'Classic Features',
        items: [
          'core/core-concepts',
          'core/indexing',
          'core/searching',
          'core/schema',
          'core/query',
          'core/backends',
          'core/dates',
          'core/nested',
          'core/sorting',
          'core/auto-indexing',
        ],
      },
      {
        type: 'category',
        label: 'Reference',
        items: [
          'core/glossary',
          'core/migration',
          'core/changelog',
          'core/legacy-cleanup',
          'core/translation-status',
        ],
      },
    ],
    Modern: [
      {type: 'doc', id: 'modern/index', label: 'Modern'},
      'modern/middleware',
      'modern/middleware-sprint-c',
      'modern/plugins',
      'modern/plugins-sprint-c',
      'modern/autocomplete',
      'modern/autocomplete-sprint-d',
      'modern/vector',
      'modern/modern-indexing',
      'modern/monitoring',
      'modern/performance',
      'modern/linguistics-sprint-d',
      'modern/stemming',
      'modern/stemming-sprint-d',
      'modern/ngrams',
      'modern/storage-providers',
    ],
  },
  // Dedicated sidebars for scoped sections — each only shows its own section
  // so that navigating to an API page, Changelog, or Example doesn't display
  // the entire site tree.
  coreSidebar: {
    Core: [
      {type: 'doc', id: 'core/index', label: 'Core'},
      'core/quickstart',
      'core/installation',
      {
        type: 'category',
        label: 'Classic Features',
        items: [
          'core/core-concepts',
          'core/indexing',
          'core/searching',
          'core/schema',
          'core/query',
          'core/backends',
          'core/dates',
          'core/nested',
          'core/sorting',
          'core/auto-indexing',
        ],
      },
      {
        type: 'category',
        label: 'Reference',
        items: [
          'core/glossary',
          'core/migration',
          'core/changelog',
          'core/legacy-cleanup',
          'core/translation-status',
        ],
      },
    ],
  },
  modernSidebar: {
    Modern: [
      {type: 'doc', id: 'modern/index', label: 'Modern'},
      'modern/middleware',
      'modern/middleware-sprint-c',
      'modern/plugins',
      'modern/plugins-sprint-c',
      'modern/autocomplete',
      'modern/autocomplete-sprint-d',
      'modern/vector',
      'modern/modern-indexing',
      'modern/monitoring',
      'modern/performance',
      'modern/linguistics-sprint-d',
      'modern/stemming',
      'modern/stemming-sprint-d',
      'modern/ngrams',
      'modern/storage-providers',
    ],
  },
  apiSidebar: {
    'API Reference': [
      'api/overview',
      'api/reference',
      {
        type: 'category',
        label: 'Core API',
        items: [
          'api/fields',
          'api/analysis',
          'api/highlight',
          'api/spelling',
          'api/sorting',
          'api/collectors',
          'api/reading',
          'api/matching',
          'api/codecs',
          'api/formats',
          'api/columns',
          'api/idsets',
          'api/automata',
          'api/classify',
          'api/lang',
        ],
      },
      {
        type: 'category',
        label: 'Modern API',
        items: [
          'api/writing',
          'api/searching',
          'api/query',
          'api/events',
          'api/middleware',
          'api/plugins',
          'api/backends',
          'api/filedb_storage',
          'api/modern',
        ],
      },
    ],
  },
  examplesSidebar: {
    Examples: [
      'examples/basic-indexing',
      'examples/search',
      'examples/search-models',
      'examples/fastapi-search',
      'examples/middleware',
      'examples/middleware-pipeline',
      'examples/movie-search',
      'examples/plugin-dev',
      'examples/data-sources',
      'examples/schema-discovery',
      'examples/facets',
      'examples/validation',
      'examples/search-view',
      'examples/autocomplete',
      'examples/vector-search',
    ],
  },
};

export default sidebars;
