"""Wiktionary-based synonym provider backed by kaikki.org JSON Lines.

Loads synonym dictionaries generated by ``update_wiktionary_dictionaries.py``
from the ``src/whoosh_modern/linguistics/dictionaries/wiktionary/`` directory.
Each JSON Lines file contains one entry per line with word-level synonyms
extracted from Wiktionary via kaikki.org.

Author: dorel14
Version: 1.0.0
"""

from __future__ import annotations

import json
import logging
from typing import Any

from whoosh_modern.linguistics.synonyms.provider import StaticSynonymProvider

logger = logging.getLogger(__name__)

_ALLOWED_POS: frozenset[str] = frozenset(
    {
        "noun",
        "verb",
        "adjective",
        "adverb",
        "proper noun",
        "preposition",
        "conjunction",
        "interjection",
        "article",
        "determiner",
        "pronoun",
    }
)


class WiktionarySynonymProvider(StaticSynonymProvider):
    """Synonym provider loading from kaikki.org JSON Lines files.

    Each line in the source file is a JSON object expected to contain at
    least ``word``, ``pos``, and ``s`` (synonyms) keys. Antonyms (``n``)
    are ignored in V1.

    Words containing spaces or empty strings are skipped, as they cannot
    be mapped as single-term synonyms.

    Args:
        path: Filesystem path to the JSON Lines dictionary file for a
            given language (e.g. ``dictionaries/wiktionary/fr.json``).
    """

    def __init__(self, path: str) -> None:
        """Initialize the provider and load synonyms from the JSON Lines file.

        Args:
            path: Filesystem path to the JSON Lines dictionary file.

        Raises:
            ValueError: If the file cannot be read or contains no valid
                entries.
        """
        self._path = path
        super().__init__()
        self._load()

    def _load(self) -> None:
        """Parse the JSON Lines file and populate the synonym mapping."""
        loaded_entries = 0
        skipped_entries = 0
        with open(self._path, encoding="utf-8") as f:
            for line_no, raw_line in enumerate(f, start=1):
                raw_line = raw_line.strip()
                if not raw_line:
                    continue
                try:
                    entry: dict[str, Any] = json.loads(raw_line)
                except json.JSONDecodeError as exc:
                    logger.warning(
                        "Skipping invalid JSON on line %d of %s: %s",
                        line_no,
                        self._path,
                        exc,
                    )
                    skipped_entries += 1
                    continue

                word = entry.get("word")
                pos = entry.get("pos")
                synonyms = entry.get("s")

                if not word or not isinstance(word, str):
                    skipped_entries += 1
                    continue

                if " " in word:
                    skipped_entries += 1
                    continue

                if pos is not None and pos not in _ALLOWED_POS:
                    skipped_entries += 1
                    continue

                if not synonyms or not isinstance(synonyms, list):
                    skipped_entries += 1
                    continue

                clean_synonyms = [
                    str(s) for s in synonyms if isinstance(s, str) and s and " " not in s
                ]
                if not clean_synonyms:
                    skipped_entries += 1
                    continue

                self.add_synonym(word, clean_synonyms)
                loaded_entries += 1

        logger.info(
            "Loaded %d entries from %s (%d skipped)",
            loaded_entries,
            self._path,
            skipped_entries,
        )
