---
name: Documentation
on:
  push:
    branches: [master, dev]
    paths:
      - "docs/**"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env:
          BUNDLE_GEMFILE: ${{ github.workspace }}/docs/Gemfile
        with:
          ruby-version: 3.0
          bundler-cache: true

      - name: Build Jekyll site
        run: bundle exec jekyll build
        env:
          BUNDLE_GEMFILE: ${{ github.workspace }}/docs/Gemfile

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4